blank_issues_enabled: false
contact_links:
  - name: Open Cloud Initative Feedback
    url: https://github.com//open-cloud-initiative/feedback/discussions
    about: Share your feedback with the Open Cloud Initiative team.